enum GameStatus {
  FIRST_BETTING = 'FIRST_BETTING',
  SECOND_BETTING = 'SECOND_BETTING',
  THIRD_BETTING = 'THIRD_BETTING',
  FINAL_BETTING = 'FINAL_BETTING',
  CHANGE_CARD = 'CHANGE_CARD',
  FOLDED = 'FOLDED',
  SHOW_DOWN = 'SHOW_DOWN',
}

export default GameStatus
